add instructions for set up
medic/cht-pipeline pull request #15
Opened 2022-12-06 06:56 UTC by njogz

This adds some instructions on how to set up the project

2022-12-12 20:54 UTC, garethbowen requested changes
Thanks! Suggestions inline.

2022-12-12 20:54 UTC, garethbowen commented on README.md
> +# Installation
Let's be more opinionated here. If these are equivalent then pick the best/easiest option. If they're not equivalent then let's document why you should pick one over the other.

Also, is this dev environment or production installation? Let's be clear.

2022-12-12 20:54 UTC, garethbowen commented on README.md
> +This project canbe run in one of two ways:
```suggestion
This project can be run in one of two ways:
```

2022-12-12 20:54 UTC, garethbowen commented on README.md
> +1. Add the path to your pipline banch to the [docker-compose.postgres.yml](https://github.com/medic/cht-sync/blob/main/docker-compose.postgres.yml#L13) file in the cht-sync project
Change this to be an environment variable. If you edit the docker-compose source directly then checking out later versions may conflict or you might accidentally commit it back to the main branch.

2022-12-12 20:54 UTC, garethbowen commented on README.md
> +1. Run docker-compose up to run the pipeline
```suggestion
1. Run `docker-compose up` to run the pipeline
```

2022-12-12 20:54 UTC, garethbowen commented on README.md
> +1. Add the path to your pipline banch to the [docker-compose.postgres.yml](https://github.com/medic/cht-sync/blob/main/docker-compose.postgres.yml#L13) file in the cht-sync project
```suggestion
1. Add the path to your pipeline branch to the [docker-compose.postgres.yml](https://github.com/medic/cht-sync/blob/main/docker-compose.postgres.yml#L13) file in the cht-sync project
```

2022-12-14 18:34 UTC, lorerod reviewed
Thanks, @njogz, for this documentation. I got my instance up and running with the instructions. I didn´t have time to look at the code in detail to know how everything works together. It may be interesting to have instructions on how to see all working together in the future, just a few steps to get a glimpse of what is happening.

2022-12-14 18:34 UTC, lorerod commented on README.md
>  1. Run `docker-compose up` to run the pipeline
Let's clarify if I have to run it on the cht-pipeline directory or the cht-sync directory.

2023-01-11 11:40 UTC, lorerod approved these changes
Thanks @njogz

2023-01-16 17:20 UTC, andrablaj requested changes
Minor typos.

2023-01-16 17:20 UTC, andrablaj commented on README.md
> +1. Run `docker-compose up` in the cht-sync directory to run the pipeline. Please ensure the `DATAEMON_INITAL_PACKAGE` env variable is set to your preferre branch of the cht-pipline repo.
```suggestion
1. Run `docker-compose up` in the cht-sync directory to run the pipeline. Please ensure the `DATAEMON_INITAL_PACKAGE` env variable is set to your preferred branch of the cht-pipeline repo. 
```

2023-01-17 12:58 UTC, andrablaj approved these changes

2023-01-26 03:59 UTC, garethbowen approved these changes
Ship it!

2023-01-26 07:06 UTC, merged