chore: remove branding from readme
medic/cht-pipeline pull request #161
Opened 2024-09-04 14:56 UTC by garethbowen

# Description

[description]

medic/pipeline#[number]

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2024-09-04 14:59 UTC, andrablaj requested changes
Tiny comment.

2024-09-04 14:59 UTC, andrablaj commented on README.md
> +Follow the instructions in [the Local CHT Sync Setup documentation](https://docs.communityhealthtoolkit.org/apps/guides/data/analytics/setup/) to set up CHT Sync with locally.
```suggestion
Follow the instructions in [the Local CHT Sync Setup documentation](https://docs.communityhealthtoolkit.org/apps/guides/data/analytics/setup/) to set up CHT Sync locally.
```

2024-09-05 05:10 UTC, garethbowen commented
Good spotting!

2024-09-05 05:30 UTC, andrablaj approved these changes
🚢

2024-09-05 05:37 UTC, merged