180 users meta base models
medic/cht-pipeline pull request #181
Opened 2024-11-14 08:36 UTC by njuguna-n

# Description

Add telemetry and feedback base models

closes #180 

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2024-11-18 12:23 UTC, witash approved these changes
LGTM

2024-11-18 13:38 UTC, jdndiaye commented
Hi @njuguna-n Are you planning to add any more telemetry to this model? Based on this [list](https://docs.communityhealthtoolkit.org/building/guides/performance/telemetry/), there's still more to add. cc @1yuv

2024-11-18 14:19 UTC, njuguna-n commented
Hello @jdndiaye, this PR is meant to provide base models similar to the [ones](https://docs.communityhealthtoolkit.org/hosting/analytics/building-dbt-models/#base-models) from the main database and not extract all available telemetry data. Are there metrics common across deployments that we should here?

2024-11-20 11:52 UTC, jdndiaye commented
> Are there metrics common across deployments that we should here?
 I know that some of them depend on the version deployed. But we can just limit ourselves to the indicators listed [here](https://docs.google.com/spreadsheets/d/1d9nI5MnPQvgAOZ3Kw6b8mvLagVIdvpS8OrVbPZYRLMw/edit?gid=1994745905#gid=1994745905).

2024-11-21 01:36 UTC, 1yuv requested changes

2024-11-21 01:36 UTC, 1yuv commented on models/users/telemetry.sql
> +    END
```suggestion
      ELSE
        '1'
    END
```

This is not correct, if day dosn't exist, we should set it to 1.

2024-12-06 13:04 UTC, merged