Brac models
medic/cht-pipeline pull request #26
Opened 2023-08-29 12:04 UTC by njuguna-n

Models  to recreate the BRAC dahsboards

2023-08-30 09:58 UTC, samuelimoisili approved these changes

2023-08-31 16:08 UTC, lorerod requested changes

2023-08-31 16:08 UTC, lorerod commented on dbt_packages/dbt_date/.gitignore
It would be better not to have `dbt_packages/dbt_date` and `dbt_packages/dbt_utils` as part of our code. 
Please add a packages.yml in the root folder to manage these dependencies. And also, add `*/dbt_packages/ `and `dbt_packages/` in the root `.gitignore`.
Or let me know if I'm getting this wrong and we need the code in our project. 
Thanks!

2023-09-14 11:31 UTC, njuguna-n commented on dbt_packages/dbt_date/.gitignore
I have made the changes requested. Please have a look @lorerod

2023-09-15 13:14 UTC, lorerod requested changes

2023-09-15 13:14 UTC, lorerod commented on dbt_packages/dbt_date/.gitignore
Thanks @njuguna-n. 
Can you please add `*/dbt_packages/ `and `dbt_packages/ `in the root `.gitignore` and, delete dbt_packages from repo? So we don't have the dependencies code in our repo? This dependencies can be installed with `dbt deps` when needed.

2023-09-18 15:32 UTC, njuguna-n commented
@lorerod `*/dbt_packages`/ and `dbt_packages/` are already in the root `gitignore` file, I have deleted the dbt_packages folder as requested.

2023-09-19 12:48 UTC, lorerod approved these changes
Thanks!

2023-09-19 19:31 UTC, lorerod commented
Hi @njuguna-n I tried to fix the failing tests when working on Add dbt unit test for BRAC models [#27](https://github.com/medic/cht-pipeline/issues/27) doing the following:
1. Modified first line in `models/brac/indexes.sql`, deleted `schema='v1', `
2. Modified `models/brac/useviews/useview_assessment_follow_up.sql`, replaced `dbt_utils.surrogate_key` for `dbt_utils.generate_surrogate_key` in line 17
With this I was able to run dbt, but the final outcome is that we have some models with errors: 
`Done. PASS=33 WARN=0 ERROR=15 SKIP=39 TOTAL=87`
 I didn't want to start changing the models code, can you please help me with that. 
 Thanks!

2023-09-26 20:41 UTC, lorerod commented
Just to clarify, what is failing is `dbt run `command before running the test. So this means the models are failing to compile.
cc: @Phil-Mwago @njuguna-n

2023-09-28 16:35 UTC, lorerod requested changes
Hi @njuguna-n, apologies for not mentioning this before. I discovered these errors while fixing the tests.

2023-09-28 16:35 UTC, lorerod commented on models/brac/indexes.sql
> +{{ config(schema='v1', materialized = 'raw_sql') }}
```suggestion
{{ config(materialized = 'raw_sql') }} 
```

2023-09-28 16:35 UTC, lorerod commented on models/brac/useviews/useview_assessment_follow_up.sql
> +{{ dbt_utils.surrogate_key(['form_source_id', 'reported', 'uuid']) }} AS useview_assessment_follow_up_source_date_uuid,
```suggestion
{{ dbt_utils.generate_surrogate_key(['form_source_id', 'reported', 'uuid']) }} AS useview_assessment_follow_up_source_date_uuid,
```

2023-09-28 16:35 UTC, lorerod commented on models/brac/impact/hhvisit/get_dashboard_data_hh_impact.sql
> +_period_start >= now() - ((1 + param_num_units::INT) || ' ' || param_interval_unit)::INTERVAL;
When compiling models with dbt run I'm getting the following:
```
16:18:34    syntax error at or near ";"
16:18:34    LINE 154: ...am_num_units::INT) || ' ' || param_interval_unit)::INTERVAL;
16:18:34                                                                            ^
16:18:34    compiled Code at target/run/pipeline/models/brac/impact/hhvisit/get_dashboard_data_hh_impact.sql
```

2023-09-28 16:35 UTC, lorerod commented on models/brac/impact/PNC/get_dashboard_data_pnc_impact.sql
> +  /* Other fields... (add the remaining fields here) */
When compiling models with dbt run I'm getting the following:
```
16:18:34    syntax error at or near "FROM"
16:18:34    LINE 58: FROM
16:18:34             ^
16:18:34    compiled Code at target/run/pipeline/models/brac/impact/PNC/get_dashboard_data_pnc_impact.sql
```

2023-09-28 16:35 UTC, lorerod commented on models/brac/impact/PNC/impact_pncview_actual_enrollments.sql
> +FROM confirmed_deliveries_CTE;
```
  syntax error at or near ";"
16:18:34    LINE 59: FROM confirmed_deliveries_CTE;
16:18:34                                          ^
16:18:34    compiled Code at target/run/pipeline/models/brac/impact/PNC/impact_pncview_actual_enrollments.sql
```

2023-09-28 16:35 UTC, lorerod commented on models/brac/impact/PNC/impact_pncview_danger_sign.sql
> +FROM pnc_danger_signs;
```
16:18:34    syntax error at or near ";"
16:18:34    LINE 34: FROM pnc_danger_signs;
16:18:34                                  ^
16:18:34    compiled Code at target/run/pipeline/models/brac/impact/PNC/impact_pncview_danger_sign.sql
```

2023-09-28 16:35 UTC, lorerod commented on models/brac/impact/ANC/impact_ancview_pregnancy_visit.sql
> +  visit_type = 'anc';
```
16:18:34    syntax error at or near ";"
16:18:34    LINE 21:   visit_type = 'anc';
16:18:34                                 ^
16:18:34    compiled Code at target/run/pipeline/models/brac/impact/ANC/impact_ancview_pregnancy_visit.sql
```

2023-09-28 16:35 UTC, lorerod commented on models/brac/contact_views/contactview_person_fields.sql
> +		person."@timestamp" AS "@timestamp"
```
16:18:34    column person.@timestamp does not exist
16:18:34    LINE 12:   person."@timestamp" AS "@timestamp"
16:18:34               ^
16:18:34    compiled Code at target/run/pipeline/models/brac/contact_views/contactview_person_fields.sql
```

2023-09-28 16:35 UTC, lorerod commented on models/brac/impact/ANC/impact_ancview_pregnancy.sql
> +INNER JOIN {{ ref('contactview_metadata') }} AS contact ON contact.uuid = preg.chw;
```
16:18:34    syntax error at or near ";"
16:18:34    LINE 41: ...contactview_metadata" AS contact ON contact.uuid = preg.chw;
16:18:34                                                                           ^
16:18:34    compiled Code at target/run/pipeline/models/brac/impact/ANC/impact_ancview_pregnancy.sql
```

2023-09-28 16:35 UTC, lorerod commented on models/brac/impact/PNC/impact_pncview_visit.sql
> +FROM pnc_visits;
```
16:18:34    syntax error at or near ";"
16:18:34    LINE 47: FROM pnc_visits;
16:18:34                            ^
16:18:34    compiled Code at target/run/pipeline/models/brac/impact/PNC/impact_pncview_visit.sql
```

2023-09-28 16:35 UTC, lorerod commented on models/brac/impact/ANC/impact_ancview_danger_sign.sql
> +  danger_sign_CTE;
```
16:18:34    syntax error at or near ";"
16:18:34    LINE 49:   danger_sign_CTE;
16:18:34                              ^
16:18:34    compiled Code at target/run/pipeline/models/brac/impact/ANC/impact_ancview_danger_sign.sql
```

2023-09-28 16:35 UTC, lorerod commented on models/brac/impact/ANC/impact_ancview_delivery.sql
> +  AND pnc.patient_id IS NOT NULL AND pnc.patient_id <> '';
```
16:18:34    syntax error at or near ";"
16:18:34    LINE 42:   AND pnc.patient_id IS NOT NULL AND pnc.patient_id <> '';
16:18:34                                                                      ^
16:18:34    compiled Code at target/run/pipeline/models/brac/impact/ANC/impact_ancview_delivery.sql
```

2023-09-28 16:35 UTC, lorerod commented on models/brac/impact/PNC/impact_pncview_expected_enrollments.sql
> +FROM pnc_expected_enrollments;
```
16:18:34    syntax error at or near ";"
16:18:34    LINE 39: FROM pnc_expected_enrollments;
16:18:34                                          ^
16:18:34    compiled Code at target/run/pipeline/models/brac/impact/PNC/impact_pncview_expected_enrollments.sql
```

2023-10-04 09:06 UTC, closed without merging