feat: Replace hardcoded values with env variables
medic/cht-pipeline pull request #73
Opened 2024-02-21 17:52 UTC by andrablaj

Closes #72

2024-02-21 17:56 UTC, andrablaj commented
@lorerod @njuguna-n I tried to do similar changes as you did for [BRAC Models](https://github.com/medic/cht-pipeline/commit/d7e70b72b6ae80213f16d98e49c0dc6e124f88dc). I didn't manage to get the unit tests pass, though. Do they pass for BRAC Models? 

There is still a `v1` hardcoded value in couchdb.sql that I didn't manage to replace by an env variable successfully at the moment.

2024-02-21 21:22 UTC, lorerod commented
>  I didn't manage to get the unit tests pass, though.

[@andrablaj](https://github.com/andrablaj), the unit tests are passing on CI. Do you mean locally?

2024-02-22 14:12 UTC, lorerod commented
@andra, hi!

> I get the same error for the main branch too when I run the tests locally.

How are you running the tests locally? 
I checked out this branch, and it is working for me locally. You must execute the three shell scripts setup every time you run the test: `setup.sh`, `run_dbt_tests.sh`, and `tear_down.sh`.

> Env var required but not provided: 'DBT_POSTGRES_USER'

This env var is setup in [this](https://github.com/medic/cht-pipeline/blob/12bbe00e115a6f8ac78c77cbb738fbc0829f19ac/tests/setup.sh#L8) line of `setup.sh`

Let me know if it works for you.

2024-02-22 15:56 UTC, andrablaj commented
@lorerod I tried the steps in the `README,` and double-checked my env variables, and they seem to align with what's needed to run the tests. As the CI passes and both you and Tom manage to run the tests locally, can you please review the PR and share comments, if any, the time I fix my local env? Thank you!

2024-02-22 18:44 UTC, andrablaj commented on packages.yml
> +  - package: calogica/dbt_date
I changed it to map[ this commit](https://github.com/medic/cht-pipeline/commit/6dc9117426799fb15323ac1369b3f81a3b62d52d) from the `BRAC-models` branch, as `main` was behind. Should I change it back?

2024-02-22 18:46 UTC, andrablaj commented on models/root/couchdb.sql
> +FROM v1.{{ env_var('POSTGRES_TABLE') }}
As mentioned [here](https://github.com/medic/cht-pipeline/pull/73#issuecomment-1957529239), I didn't manage to get that working. I will try again tomorrow.

2024-02-22 21:01 UTC, lorerod requested changes
Hello @andrablaj! Thank you for making the improvements. I have a few minor suggestions to make. 

Before we merge this to the main branch, I think we need to ensure that the `cht-sync` tests pass with this version of `cht-pipeline`, right @njuguna-n?
I can check when you have a final version of this, and if the tests are not passing, I will create an issue on that repository and make sure this is mentioned as a dependency.
What do you think?

2024-02-23 06:15 UTC, njuguna-n commented
@lorerod yes, I agree that we need to have tests passing.

2024-02-26 15:17 UTC, merged