98 rename @timestamp column
medic/cht-pipeline pull request #99
Opened 2024-06-27 09:50 UTC by njuguna-n

# Description

Rename the @timestamp column.

This PR depends on [this](https://github.com/medic/cht-sync/pull/117) on in the cht-sync repo.

medic/pipeline#98

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2024-07-01 06:50 UTC, njuguna-n commented
@lorerod please review.

2024-07-02 19:05 UTC, lorerod requested changes
@njuguna-n, thank you for these changes. I suggest using lowercase with an underscore naming convention for Postgresql table column names. Let me know what you think.

2024-07-02 19:05 UTC, lorerod commented on models/contacts/contact.sql
> +      {'columns': ['savedTimestamp']},
```suggestion
      {'columns': ['saved_timestamp']},
```

2024-07-02 19:05 UTC, lorerod commented on models/contacts/contact.sql
> +  savedTimestamp,
```suggestion
  saved_timestamp,
```

2024-07-02 19:05 UTC, lorerod commented on models/contacts/contact.sql
> +  AND savedTimestamp >= {{ max_existing_timestamp('savedTimestamp') }}
```suggestion
  AND saved_timestamp >= {{ max_existing_timestamp('saved_timestamp') }}
```

2024-07-02 19:05 UTC, lorerod commented on models/contacts/patient.sql
> +      {'columns': ['savedTimestamp'], 'type': 'btree'},
```suggestion
      {'columns': ['saved_timestamp'], 'type': 'btree'},
```

2024-07-02 19:05 UTC, lorerod commented on models/contacts/patient.sql
> +  person.savedTimestamp,
```suggestion
  person.saved_timestamp,
```

2024-07-02 19:05 UTC, lorerod commented on models/contacts/patient.sql
> +  AND person.savedTimestamp >= {{ max_existing_timestamp('savedTimestamp') }}
```suggestion
  AND person.saved_timestamp >= {{ max_existing_timestamp('saved_timestamp') }}
```

2024-07-02 19:05 UTC, lorerod commented on models/contacts/person.sql
> +      {'columns': ['savedTimestamp']},
```suggestion
      {'columns': ['saved_timestamp']},
```

2024-07-02 19:05 UTC, lorerod commented on models/contacts/person.sql
> +  contact.savedTimestamp,
```suggestion
  contact.saved_timestamp,
```

2024-07-02 19:05 UTC, lorerod commented on models/contacts/person.sql
> +  AND contact.savedTimestamp >= {{ max_existing_timestamp('savedTimestamp') }}
```suggestion
  AND contact.saved_timestamp >= {{ max_existing_timestamp('saved_timestamp') }}
```

2024-07-02 19:05 UTC, lorerod commented on models/contacts/place.sql
> +      {'columns': ['savedTimestamp']},
```suggestion
      {'columns': ['saved_timestamp']},
```

2024-07-02 19:05 UTC, lorerod commented on models/contacts/place.sql
> +  contact.savedTimestamp,
```suggestion
  contact.saved_timestamp,
```

2024-07-02 19:05 UTC, lorerod commented on models/contacts/place.sql
> +  AND contact.savedTimestamp >= {{ max_existing_timestamp('savedTimestamp') }}
```suggestion
  AND contact.saved_timestamp >= {{ max_existing_timestamp('saved_timestamp') }}
```

2024-07-02 19:05 UTC, lorerod commented on models/forms/data_record.sql
> +      {'columns': ['savedTimestamp']},
```suggestion
      {'columns': ['saved_timestamp']},
```

2024-07-02 19:05 UTC, lorerod commented on models/forms/data_record.sql
> +  savedTimestamp,
```suggestion
  saved_timestamp,
```

2024-07-02 19:05 UTC, lorerod commented on models/forms/data_record.sql
> +  AND savedTimestamp >= {{ max_existing_timestamp('savedTimestamp') }}
```suggestion
  AND saved_timestamp >= {{ max_existing_timestamp('saved_timestamp') }}
```

2024-07-02 19:05 UTC, lorerod commented on models/users/user.sql
> +      {'columns': ['savedTimestamp']},
```suggestion
      {'columns': ['saved_timestamp']},
```

2024-07-02 19:05 UTC, lorerod commented on models/users/user.sql
> +  savedTimestamp,
```suggestion
  saved_timestamp,
```

2024-07-02 19:05 UTC, lorerod commented on models/users/user.sql
> +  AND savedTimestamp >= {{ max_existing_timestamp('savedTimestamp') }}
```suggestion
  AND saved_timestamp >= {{ max_existing_timestamp('saved_timestamp') }}
```

2024-07-02 19:05 UTC, lorerod commented on tests/setup.sh
> +      savedTimestamp timestamp NULL,
```suggestion
      saved_timestamp timestamp NULL,
```

2024-07-03 14:28 UTC, lorerod approved these changes

2024-07-04 07:22 UTC, merged